### ISSUE TITLE
Source "truffle/Assert.sol" not found

### ISSUE THREAD

**Issue by galimba** [truffle-box/pet-shop-box#32]
While trying to compile the `TestAdoption.sol` part of the tutorial, I come across this issue.

the code is:

pragma solidity ^0.4.17;

import "truffle/Assert.sol";
import "truffle/DeployedAddress.sol";
import "../contracts/Adoption.sol";

contract TestAdoption{
    Adoption adoption= Adoption(DeployedAddresses.Adoption());
}

**Comment by galimba** [comment]
I also get "Source "truffle/DeployedAddress.sol" not found"

**Comment by vincentcheny** [comment]
I got the same problem here. And I am using
Truffle v4.1.14
Solidity v0.4.24

Some answers say that using some older versions like Truffle v4.1.4 can be a solution, but after I try so, another error "ParserError: Expected identifier" shows up because the version of Solidity is too old.

**Comment by DevelopersTopHat** [comment]
This issue persists for version 5.0.9 on Windows 10 64 bit.

**Comment by kevinmcfarlane** [comment]
Same for me on 5.0.9, Win 10 64, VS Code.

**Comment by Lilith1410** [comment]
same for me on Ubuntu 18.04

**Comment by modianar** [comment]
Truffle v5.0.7 (core: 5.0.7)
Solidity v0.5.0 (solc-js)
Node v8.15.0

Try With this version

**Comment by kypanz** [comment]
> While trying to compile the `TestAdoption.sol` part of the tutorial, I come across this issue.
> 
> the code is:
> 
> pragma solidity ^0.4.17;
> 
> import "truffle/Assert.sol";
> import "truffle/DeployedAddress.sol";
> import "../contracts/Adoption.sol";
> 
> contract TestAdoption{
> Adoption adoption= Adoption(DeployedAddresses.Adoption());
> }

English / ( i have bad english but i try )
Hello , the problem may be is you are typing wrong the tutorial, because you say :
- import "truffle/DeployedAddress.sol";
and i think is :
- import "truffle/DeployedAddresses.sol";
the same in :
- Adoption adoption = Adoption(DeployedAddresses.Adoption()); // This is correcly because you are saying "Addresses" and not "Address"
and the pragma in this date says : "0.5.0" , but really i dont know what version used in that date.
Try to change and see what happends

/ Spanish :
Hola el probleme posiblemente sea que tipeas o escribes mal el tutorial , ya que dice "truffle/DeployedAddresses.sol" ( en el tutorial ) y no "truffle/DeplyedAddress.sol"
en el mismo codigo que se ve luego intentas ocuparlo llamandolo correctamente "DeployedAddresses.Adoption()" , esto esta bien por que dice "Addresses" y no "Address"
creo que ese es el problema
Por otro lado en el tutorial hace referencia a pragma " 0.5.0 " y no la version que escribes , pero eso depende ya que en esa fecha seguramente se ocupaba otro pragma, esto ya es mas relativo.

Good bye All <3

**Comment by endepointe** [comment]
I am using solidity ^0.7.0 and am receiving the same error. I will look for a work-around that doesn't include reverting to an older compiler version.
